name: myproduction
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.9
  flutter_email_sender: ^5.1.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  shared_preferences: ^2.0.13
  cloud_firestore: ^3.1.7
  flutter_slidable: ^1.2.0
  flutter_ringtone_player: ^3.1.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  hooks_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
flutter:
  uses-material-design: true